use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

use crate::cli::Opts;
use crate::config::DepPattern;
use crate::service::{self, Service};
use anyhow::Result;

pub fn calculate(opts: Opts) -> Result<()> {
    let services = service::Service::discover(&opts)?;
    let uniques = unique_service_names(services);

    println!("// Auto-generated by monodeps [https://github.com/kongo2002/monodeps]");
    println!();
    println!("digraph dependencies {{");

    for (ident, svc) in &uniques {
        println!("  {} [label=\"{}\"];", ident.id, ident.name);

        let deps = svc
            .auto_dependencies
            .iter()
            .map(|auto| &auto.pattern)
            .chain(svc.depsfile.dependencies.iter());

        let mut seen = HashSet::new();

        for pattern in deps {
            if let Some(dependency) = find_dependent_service(pattern, &uniques) {
                if !seen.insert(dependency.id.clone()) {
                    continue;
                }
                println!("  {} -> {};", ident.id, dependency.id);
            }
        }
        println!();
    }

    println!("}}");

    Ok(())
}

fn find_dependent_service<'a>(
    pattern: &DepPattern,
    others: &'a HashMap<ServiceIdent, Service>,
) -> Option<&'a ServiceIdent> {
    for (ident, svc) in others {
        if pattern.is_child_of(&svc.path.canonicalized) {
            return Some(ident);
        }
    }

    None
}

#[derive(Hash, PartialEq, Eq)]
struct ServiceIdent {
    id: String,
    name: String,
}

fn unique_service_names(services: Vec<Service>) -> HashMap<ServiceIdent, Service> {
    let num_services = services.len();

    let mut ancestors = 0;

    for ancestor_count in [0usize, 1, 2, 3] {
        let service_names = get_service_names(&services, ancestor_count);
        if service_names.len() == num_services {
            ancestors = ancestor_count;
            break;
        }
    }

    services
        .into_iter()
        .enumerate()
        .map(|(idx, svc)| {
            (
                ServiceIdent {
                    id: format!("service_{}", idx + 1),
                    name: service_identifier(&svc, ancestors),
                },
                svc,
            )
        })
        .collect()
}

fn get_service_names(services: &[Service], num_ancestors: usize) -> HashSet<String> {
    services
        .iter()
        .map(|svc| service_identifier(svc, num_ancestors))
        .collect()
}

fn service_identifier(service: &Service, num_ancestors: usize) -> String {
    let path = PathBuf::from(&service.path.canonicalized);
    let mut parts: Vec<_> = path
        .components()
        .rev()
        .take(num_ancestors + 1)
        .flat_map(|prt| prt.as_os_str().to_str())
        .collect();
    parts.reverse();
    parts.join(".")
}
